version: '3.4'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports: 
      - 27017:27017
    networks:
      backend:

  java:
    image: spring-mongo
    container_name: java
    restart: always
    environment:
      MONGODB_URI: "mongodb://mongo:27017/project-springboot-nosql-mongodb"
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      backend:
networks:
  backend:
    
